settings:
  app_title: 'Birdvision'
  service_tax: 12.36
  company_name: 'Birdvision Consulting Pvt. Ltd.'
  company_address: '35, BIZZBAY, Opp. Clover Hills, N.I.B.M. Road, Kondhwa, Pune – 411048 Tel.: 020-6606 2774'
  service_tax_number: 'AAECB3976FSD001'
  service_tax_category: 'Auxillary Services'
  pan_number: 'AAECB3976F'
  accounts_email: 'accounts@birdvision.in'